### ISSUE TITLE
Offer minimal license if possible

### ISSUE THREAD

**Issue by a3nm** [wetneb/dissemin#103]
arxiv.org makes it possible to deposit papers with a "minimal license" which is just saying that arXiv has permission to distribute the file: http://arxiv.org/licenses/nonexclusive-distrib/1.0/license.html

For authors who aren't sure about whether they have the right to license their work under Creative Commons license, this can be an important feature.

An option to deposit under such a license should be offered, if Zenodo allows one. If it does not, ideally a repository allowing this license should be added.

**Comment by wetneb** [comment]
I have not found such a license in the list proposed by Zenodo (they say we can ask them to add new ones, though):
https://zenodo.org/kb/export?kbname=licenses
Adding arXiv support is not impossible - a lot of the code written for HAL could be reused.
