### ISSUE TITLE
Virtualbox VM should only accept SSH connections from localhost by default

### ISSUE THREAD

**Issue by a3nm** [wetneb/dissemin#105]
The INSTALL file recommends the use of a VM, http://pintoch.ulminfo.fr/DisseminVM.ova, which by default runs an SSH server, which listen for incoming connections from outside machines.

As the default SSH password is very weak, this is not a good idea, it should be changed by adding to /etc/ssh/sshd_config the following:

ListenAddress 127.0.0.1
ListenAddress ::1

**Comment by wetneb** [comment]
How is that insecure? Any attacker could indeed spoil the VM, but nothing else, right? I mean, the VM is only intended for dev. (But it's probably easy to fix anyway)

**Comment by a3nm** [comment]
Sure, assuming Virtualbox is secure the attacker would remain in the VM, but they could then use the VM's ressources, network connectivity, etc. (e.g., use the victim computer as a proxy), which is not great. :)
