### ISSUE TITLE
django-cas

### ISSUE THREAD

**Issue by threonorm** [wetneb/dissemin#11]
We "fixed" django CAS in a crappy way. We should investigate to check if this fix does not break anything else. A function was called with a variable number of arguments, but the wrapper was not considering this, so we added these arguments and we just throw them.

**Comment by wetneb** [comment]
Why don't we use `django-cas-ng`, the new version of `django-cas`? Looks like they have implemented lots of nice features. They have probably fixed your bug too (otherwise, they are still active, so we can do a pull request).

https://github.com/mingchen/django-cas-ng
