### ISSUE TITLE
OpenAIRE links

### ISSUE THREAD

**Issue by p4bl0-** [wetneb/dissemin#123]
When a paper info are retrieved from OpenAIRE, the "OpenAIRE" link next to the "download" button links to the same URL as the button. That is confusing. Proposed fix: the "OpenAIRE" text should not be a link.

**Comment by wetneb** [comment]
So we keep links when they point to another page (a splash page, instead of a direct link to the PDF) ?
Or do we simply remove links for all sources like this one ?

**Comment by p4bl0-** [comment]
I think we should remove these links altogether. They are inconsistent with the rest of the website. Usually the text next to the download button is the name of the venue in which the article has been published, and when this text is also a link it is an internal link to dissemin's page about this venue.
