### ISSUE TITLE
installation fail

### ISSUE THREAD

**Issue by sexybee** [wetneb/dissemin#137]
I've followed the install instructions step by step but when I do "pip install -r requirements_frontend.txt", i get this error : ValueError: --enable-jpeg requested but jpeg not found, aborting.
It seems that I'm having a problem with the pillow plugin..

I'm using a fresh new Ubuntu VM..

**Comment by sexybee** [comment]
ok I had to install libjpeg , so sudo apt-get install libjpeg-dev did the trick..
(I had also to install kombu and billiard with pip to make the thing work..)

**Comment by wetneb** [comment]
Thanks for pointing that out, I have just updated the docs with this additional dependency.

**Comment by wetneb** [comment]
We also have a Debian VM ready to use:
http://dev.dissem.in/doc/vm.html
