### ISSUE TITLE
Add an API

### ISSUE THREAD

**Issue by wetneb** [wetneb/dissemin#174]
Easiest thing: just use the existing JSON dump methods to expose all we have for a given paper.

**Comment by wetneb** [comment]
We should also add a way for the OA button to be notified when we have new deposits. A callback? Or a list of the recent deposits that they would poll? @markmacgillivray @JosephMcArthur

**Comment by markmacgillivray** [comment]
I'm not sure new deposit notification is hugely useful for oabutton - we
just check when a user is on a page. So, being able to query if you have
something or not is the main use. However an ability to get notified or to
query for new deposits would certainly be useful in general, particularly
for other catalogue systems wanting to stay in sync (one of which I may
also be running ;)

**Comment by wetneb** [comment]
Draft API implemented, docs are here: http://dev.dissem.in/api.html
