### ISSUE TITLE
Fingerprints: convert latex to plain text ?

### ISSUE THREAD

**Issue by wetneb** [wetneb/dissemin#35]
ex: $\mathbb{NP}$ -> NP

**Comment by Phyks** [comment]
Or use mathjax ? =)

**Comment by wetneb** [comment]
@Phyks : we already use mathjax. :-)
The thing is that if a paper appears in one source as "Tackling $\mathbb{P}$ versus $\mathbb{NP}$" and in another as "Tackling P vs NP", we want to be able to identify the two… Hence some latex to plain text conversion, don't you think? (only internally of course, the website continues to display the latex version with mathjax :-) )

**Comment by Phyks** [comment]
Oups, my bad, i read the issue too fast =(

:+1: For plain text conversion :) Something like detex ? https://code.google.com/p/opendetex/

**Comment by wetneb** [comment]
Yeah, sounds like the right thing. But ideally I was dreaming of a python library to do that…

(well, the issue wasn't very detailed :-P )

**Comment by wetneb** [comment]
This is what we need: https://pypi.python.org/pypi/unicode_tex
Ensure it is efficient.
