### ISSUE TITLE
Abstract field is sometimes initially empty when depositing papers

### ISSUE THREAD

**Issue by a3nm** [wetneb/dissemin#81]
When depositing papers it sometimes happens that the "Abstract" textarea in the "Review metadata" phase is empty. However, once the deposit is completed (even with an empty PDF), the abstract is correctly filled, suggesting that the abstract was in fact known and should have been displayed earlier.

**Comment by wetneb** [comment]
In fact, the abstract is fetched on the fly during deposit (using Zotero) when it is not available yet. This is not done systematically for all papers without abstracts because it is time-consuming and we might end up being blocked by the publishers (as it scrapes their paywalls).

**Comment by a3nm** [comment]
OK, but then it should be done when the depositing process is initiated, so that the abstract field is correctly pre-filled.

**Comment by wetneb** [comment]
yep. So we need an AJAX-based method that fetches asynchronously the abstract and updates the form if we get it… We can't afford to fetch it before displaying the form, I think, because it can take some time.

**Comment by a3nm** [comment]
Yes, usability-wise it would be better for it to be AJAX-based.
